name: Lint Checks

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: "yarn"
      - name: Run Lint
        run: |
          yarn install --immutable
          yarn lint
